apiVersion: apps/v1
kind: Deployment
metadata:
  name: pravnamreza
  labels:
    app: pravnamreza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pravnamreza
  template:
    metadata:
      labels:
        app: pravnamreza
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: collectstatic
          image: pravnamreza
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: APP_ENV
              value: production
            - name: PYTHONPATH
              value: /code:$PYTHONPATH
            - name: DJANGO_SETTINGS_MODULE
              value: pravnamreza.settings.production
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
        - name: migrate
          image: pravnamreza
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: APP_ENV
              value: production
            - name: PYTHONPATH
              value: /code:$PYTHONPATH
            - name: DJANGO_SETTINGS_MODULE
              value: pravnamreza.settings.production
          envFrom:
            - secretRef:
                name: pmvd-config
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
      containers:
        - name: pravnamreza
          image: pravnamreza # kustomize thing
          command:
            - gunicorn
            - pravnamreza.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: APP_ENV
              value: production
            - name: PYTHONPATH
              value: /code:$PYTHONPATH
            - name: DJANGO_SETTINGS_MODULE
              value: pravnamreza.settings.production
          envFrom:
            - secretRef:
                name: pmvd-config
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
