apiVersion: apps/v1
kind: Deployment
metadata:
  name: pravnamreza
  labels:
    app: pravnamreza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pravnamreza
  template:
    metadata:
      labels:
        app: pravnamreza
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: pravnamreza-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: pravnamreza
          volumeMounts:
            - name: pravnamreza-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: APP_ENV
              value: production
            - name: PYTHONPATH
              value: /code:$PYTHONPATH
            - name: DJANGO_SETTINGS_MODULE
              value: pravnamreza.settings.production
          envFrom:
            - secretRef:
                name: pmvd-config
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 200Mi
              cpu: 200m
        - name: migrate
          image: pravnamreza
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: APP_ENV
              value: production
            - name: PYTHONPATH
              value: /code:$PYTHONPATH
            - name: DJANGO_SETTINGS_MODULE
              value: pravnamreza.settings.production
          envFrom:
            - secretRef:
                name: pmvd-config
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 200Mi
              cpu: 200m
      containers:
        - name: pravnamreza
          image: pravnamreza
          volumeMounts:
            - name: pravnamreza-storage
              mountPath: /storage
          command:
            - gunicorn
            - pravnamreza.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "90"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: APP_ENV
              value: production
            - name: PYTHONPATH
              value: /code:$PYTHONPATH
            - name: DJANGO_SETTINGS_MODULE
              value: pravnamreza.settings.production
          envFrom:
            - secretRef:
                name: pmvd-config
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 400Mi
              cpu: 200m
        - name: pravnamreza-nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          image: nginx:alpine
          volumeMounts:
            - name: pravnamreza-storage
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 50m      