apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pravnamreza-staging
resources:
  - backend.yaml
images:
  - name: pravnamreza-staging
    newName: rg.fr-par.scw.cloud/djnd/pravna-mreza-staging.si
    newTag: '7bb60318c59d7b3c52089227b2c04f5b79908769'
