volumes:
  postgres-data:

services:
  web:
    container_name: "web"
    build: ./pravna-mreza.si
    working_dir: /code
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pravna-mreza.si:/code:delegated,rw
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /code:$PYTHONPATH
      DJANGO_SETTINGS_MODULE: pravnamreza.settings.production
      DJANGO_DEBUG: "yes"
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
