# Generated by Django 3.1.14 on 2021-12-20 17:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField()),
                ('preview_text', wagtail.fields.RichTextField(default='')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MonitoringArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline_first', models.TextField(blank=True, verbose_name='Naslovnica prvi del')),
                ('headline_second', models.TextField(blank=True, verbose_name='Naslovnica drugi del')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis')),
                ('get_in_touch', models.URLField(blank=True, null=True, verbose_name='Povezava v opisu')),
                ('headline_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Slika na naslovnici')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
