# Generated by Django 3.1.14 on 2021-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringarchivepage',
            name='get_in_touch_text',
            field=models.TextField(blank=True, verbose_name='Ime povezave'),
        ),
    ]
