# Generated by Django 3.1.14 on 2021-12-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_monitoringarchivepage_get_in_touch_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monitoringarchivepage",
            options={
                "verbose_name": "Seznam poročil",
                "verbose_name_plural": "Seznam poročil",
            },
        ),
        migrations.AlterModelOptions(
            name="monitoringpage",
            options={"verbose_name": "Poročilo", "verbose_name_plural": "Poročilo"},
        ),
    ]
