# Generated by Django 3.1.4 on 2020-12-31 12:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_genericpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('part_one', wagtail.blocks.CharBlock()), ('part_two', wagtail.blocks.CharBlock()), ('intro_text', wagtail.blocks.RichTextBlock())], icon='title')), ('paragraph', wagtail.blocks.RichTextBlock())], default=''),
            preserve_default=False,
        ),
    ]
