# Generated by Django 3.1.4 on 2021-01-20 10:14

import wagtail.blocks
import wagtail.blocks.static_block
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_ogsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [
                                ("part_one", wagtail.blocks.CharBlock(required=False)),
                                ("part_two", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "intro_text",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                            ],
                            icon="title",
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "DonationEmbed",
                        wagtail.blocks.static_block.StaticBlock(
                            admin_text="Donation embed"
                        ),
                    ),
                ]
            ),
        ),
    ]
