# Generated by Django 3.1.4 on 2021-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_infopush"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infopush",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
