# Generated by Django 3.1.5 on 2021-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210127_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('source', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
