# Generated by Django 3.1.10 on 2021-07-12 12:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0011_objava'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationEmbedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('embed_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('part_one', wagtail.blocks.CharBlock(required=False)), ('part_two', wagtail.blocks.CharBlock(required=False)), ('intro_text', wagtail.blocks.RichTextBlock(required=False))], icon='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('donation_section', wagtail.blocks.StructBlock([('left_button_heading_part_one', wagtail.blocks.CharBlock(required=False)), ('left_button_heading_part_two', wagtail.blocks.CharBlock(required=False)), ('left_button_description', wagtail.blocks.CharBlock(required=False)), ('left_button_donation_page', wagtail.blocks.PageChooserBlock(label='Povezava do strani')), ('right_heading_part_one', wagtail.blocks.CharBlock(required=False)), ('right_heading_part_two', wagtail.blocks.CharBlock(required=False)), ('right_button_description', wagtail.blocks.CharBlock(required=False)), ('right_button_donation_page', wagtail.blocks.PageChooserBlock(label='Povezava do strani'))]))]),
        ),
    ]
