# Generated by Django 3.1.10 on 2021-07-12 13:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210712_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('part_one', wagtail.core.blocks.CharBlock(required=False)), ('part_two', wagtail.core.blocks.CharBlock(required=False)), ('intro_text', wagtail.core.blocks.RichTextBlock(required=False))], icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('donation_section', wagtail.core.blocks.StructBlock([('left_button_heading_part_one', wagtail.core.blocks.CharBlock(required=False)), ('left_button_heading_part_two', wagtail.core.blocks.CharBlock(required=False)), ('left_button_description', wagtail.core.blocks.CharBlock(required=False)), ('left_button_donation_page', wagtail.core.blocks.PageChooserBlock(label='Povezava do strani')), ('right_button_heading_part_one', wagtail.core.blocks.CharBlock(required=False)), ('right_button_heading_part_two', wagtail.core.blocks.CharBlock(required=False)), ('right_button_description', wagtail.core.blocks.CharBlock(required=False)), ('right_button_donation_page', wagtail.core.blocks.PageChooserBlock(label='Povezava do strani'))]))]),
        ),
    ]
