# Generated by Django 3.1.10 on 2021-12-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("home", "0014_auto_20210712_1326"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
            ],
            options={
                "verbose_name": "Urejanje naročnine",
                "verbose_name_plural": "Urejanja naročnin",
            },
            bases=("wagtailcore.page",),
        ),
    ]
