# Generated by Django 3.1.10 on 2021-12-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("home", "0022_auto_20211210_1403"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="description_text",
        ),
        migrations.AddField(
            model_name="homepage",
            name="blog_section_archive_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Povezava do seznama blog zapisov",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="blog_section_archive_link_title",
            field=models.TextField(
                default="Vsi zapisi",
                verbose_name="Ime povezave do seznama blog zapisov",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="blog_section_title",
            field=models.TextField(
                default="Pravni blog", verbose_name="Naslov blog sekcije"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="facebook_link",
            field=models.URLField(
                default="https://www.facebook.com/pravnamreza/",
                verbose_name="Facebook URL",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="monitor_button",
            field=models.TextField(
                default="OGLASI SE NAM!", verbose_name="Škatla monitoring - gumb"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="monitor_text",
            field=models.TextField(
                default="Prispevaj pravniško znanje.",
                verbose_name="Škatla monitoring - opis",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="monitor_title_part_one",
            field=models.TextField(
                default="Nadzoruj", verbose_name="Škatla monitoring - naslov 1. del"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="monitor_title_part_two",
            field=models.TextField(
                default="PROTESTE", verbose_name="Škatla monitoring - naslov 2. del"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="news_section_archive_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Povezava do seznama novic",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="news_section_archive_link_title",
            field=models.TextField(
                default="Arhiv novic", verbose_name="Ime povezave do seznama novic"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="news_section_title",
            field=models.TextField(
                default="Novice", verbose_name="Naslov sekcije z novicami"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_button",
            field=models.TextField(
                default="PRIJAVI SE", verbose_name="Škatla novičnik - gumb"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_terms",
            field=models.TextField(
                default="Strinjam se, da mi Danes je nov dan v imenu Pravne mreže za varstvo demokracije občasno pošlje email.",
                verbose_name="Škatla novičnik - pogoji",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_title_part_one",
            field=models.TextField(
                default="NAŠE NOVICE", verbose_name="Škatla novičnik - naslov 1. del"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_title_part_two",
            field=models.TextField(
                default="NASE NOVICE", verbose_name="Škatla novičnik - naslov 2. del"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="social_media_title_part_one",
            field=models.TextField(
                default="Sledi nam na",
                verbose_name="Škatla socialna omrežja - naslov 1. del",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="social_media_title_part_two",
            field=models.TextField(
                default="DRUŽBENIH OMREŽJIH",
                verbose_name="Škatla socialna omrežja - naslov 2. del",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="support_button",
            field=models.TextField(
                default="DONIRAJ", verbose_name="Škatla podpri - gumb"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="support_text",
            field=models.TextField(
                default="Prispevaj sredstva za pomoc protestnikom.",
                verbose_name="Škatla podpri - opis",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="support_title_part_one",
            field=models.TextField(
                default="Podpri", verbose_name="Škatla podpri - naslov 1. del"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="support_title_part_two",
            field=models.TextField(
                default="PRAVNO MREŽO", verbose_name="Škatla podpri - naslov 2. del"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="twitter_link",
            field=models.URLField(
                default="https://twitter.com/PravnaMreza/", verbose_name="Twitter URL"
            ),
            preserve_default=False,
        ),
    ]
