# Generated by Django 3.1.14 on 2021-12-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0026_auto_20211216_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='monitor_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Škatla monitoring - gumb povezava'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='support_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Škatla podpri - gumb povezava'),
        ),
    ]
