# Generated by Django 3.1.14 on 2021-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211216_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blog_section_archive_link_title',
            field=models.TextField(blank=True, verbose_name='Ime povezave do seznama blog zapisov'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_section_title',
            field=models.TextField(blank=True, verbose_name='Naslov blog sekcije'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='monitor_button',
            field=models.TextField(blank=True, verbose_name='Škatla monitoring - gumb'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='monitor_text',
            field=models.TextField(blank=True, verbose_name='Škatla monitoring - opis'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='monitor_title_part_one',
            field=models.TextField(blank=True, verbose_name='Škatla monitoring - naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='monitor_title_part_two',
            field=models.TextField(blank=True, verbose_name='Škatla monitoring - naslov 2. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_section_archive_link_title',
            field=models.TextField(blank=True, verbose_name='Ime povezave do seznama novic'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_section_title',
            field=models.TextField(blank=True, verbose_name='Naslov sekcije z novicami'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='newsletter_failure',
            field=models.TextField(blank=True, verbose_name='Škatla novičnik - sporočilo ob neuspešni prijavi'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='newsletter_success',
            field=models.TextField(blank=True, verbose_name='Škatla novičnik - sporočilo ob uspešni prijavi'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='newsletter_terms',
            field=models.TextField(blank=True, verbose_name='Škatla novičnik - pogoji'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='newsletter_title_part_one',
            field=models.TextField(blank=True, verbose_name='Škatla novičnik - naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='newsletter_title_part_two',
            field=models.TextField(blank=True, verbose_name='Škatla novičnik - naslov 2. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_media_title_part_one',
            field=models.TextField(blank=True, verbose_name='Škatla socialna omrežja - naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_media_title_part_two',
            field=models.TextField(blank=True, verbose_name='Škatla socialna omrežja - naslov 2. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='support_button',
            field=models.TextField(blank=True, verbose_name='Škatla podpri - gumb'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='support_text',
            field=models.TextField(blank=True, verbose_name='Škatla podpri - opis'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='support_title_part_one',
            field=models.TextField(blank=True, verbose_name='Škatla podpri - naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='support_title_part_two',
            field=models.TextField(blank=True, verbose_name='Škatla podpri - naslov 2. del'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='twitter_link',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
