# Generated by Django 3.1.14 on 2021-12-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0028_auto_20211217_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='social_media_title_part_one',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='social_media_title_part_two',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='twitter_link',
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_title_part_one', models.TextField(blank=True, verbose_name='Škatla socialna omrežja - naslov 1. del')),
                ('social_media_title_part_two', models.TextField(blank=True, verbose_name='Škatla socialna omrežja - naslov 2. del')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Socialna omrežja',
            },
        ),
    ]
