# Generated by Django 3.1.14 on 2021-12-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0030_auto_20211217_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='support_button',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='support_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='support_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='support_title_part_one',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='support_title_part_two',
        ),
        migrations.CreateModel(
            name='SupportBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_title_part_one', models.TextField(blank=True, verbose_name='Škatla podpri - naslov 1. del')),
                ('support_title_part_two', models.TextField(blank=True, verbose_name='Škatla podpri - naslov 2. del')),
                ('support_text', models.TextField(blank=True, verbose_name='Škatla podpri - opis')),
                ('support_button', models.TextField(blank=True, verbose_name='Škatla podpri - gumb')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('support_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Škatla podpri - gumb povezava')),
            ],
            options={
                'verbose_name': 'Donacije',
            },
        ),
    ]
