# Generated by Django 3.1.14 on 2021-12-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0031_auto_20211217_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportBox',
            new_name='Support',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='monitor_button',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='monitor_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='monitor_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='monitor_title_part_one',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='monitor_title_part_two',
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_title_part_one', models.TextField(blank=True, verbose_name='Škatla monitoring - naslov 1. del')),
                ('monitor_title_part_two', models.TextField(blank=True, verbose_name='Škatla monitoring - naslov 2. del')),
                ('monitor_text', models.TextField(blank=True, verbose_name='Škatla monitoring - opis')),
                ('monitor_button', models.TextField(blank=True, verbose_name='Škatla monitoring - gumb')),
                ('monitor_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Škatla monitoring - gumb povezava')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Prispevaj',
            },
        ),
    ]
