# Generated by Django 3.1.14 on 2021-12-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0033_homepage_monitor_archive_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objava',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_button',
            field=models.TextField(blank=True, verbose_name='Besedilo na gumbu'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Povezava'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_text',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_title_part_one',
            field=models.TextField(blank=True, verbose_name='Naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_title_part_two',
            field=models.TextField(blank=True, verbose_name='Naslov 2. del'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_failure',
            field=models.TextField(blank=True, verbose_name='Sporočilo ob neuspešni prijavi'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_success',
            field=models.TextField(blank=True, verbose_name='Sporočilo ob uspešni prijavi'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_terms',
            field=models.TextField(blank=True, verbose_name='Novičnik pogoji'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_title_part_one',
            field=models.TextField(blank=True, verbose_name='Naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_title_part_two',
            field=models.TextField(blank=True, verbose_name='Naslov 2. del'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media_title_part_one',
            field=models.TextField(blank=True, verbose_name='Naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media_title_part_two',
            field=models.TextField(blank=True, verbose_name='Naslov 2. del'),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_button',
            field=models.TextField(blank=True, verbose_name='Besedilo na gumbu'),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Povezava'),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_text',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_title_part_one',
            field=models.TextField(blank=True, verbose_name='Naslov 1. del'),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_title_part_two',
            field=models.TextField(blank=True, verbose_name='Naslov 2. del'),
        ),
    ]
