# Generated by Django 3.1.14 on 2021-12-22 11:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_footersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='footer_links_left',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Če je prazno se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Stran')), ('has_border', wagtail.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('external_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('url', wagtail.blocks.URLBlock(label='Povezava')), ('has_border', wagtail.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('email_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('url', wagtail.blocks.EmailBlock(label='Email povezava'))]))], verbose_name='Povezave v nogi na levi'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_links_right',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Če je prazno se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Stran')), ('has_border', wagtail.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('external_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('url', wagtail.blocks.URLBlock(label='Povezava')), ('has_border', wagtail.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('email_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('url', wagtail.blocks.EmailBlock(label='Email povezava'))]))], verbose_name='Povezave v nogi na desni'),
        ),
    ]
