# Generated by Django 3.1.14 on 2021-12-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20211226_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationembedpage',
            options={'verbose_name': 'Stran za donacijo', 'verbose_name_plural': 'Strani za donacijo'},
        ),
        migrations.AlterModelOptions(
            name='genericpage',
            options={'verbose_name': 'Generična stran', 'verbose_name_plural': 'Generične strani'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Domača stran', 'verbose_name_plural': 'Domače strani'},
        ),
    ]
