# Generated by Django 3.1.14 on 2022-01-17 15:57

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20211226_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='headline_first',
            field=models.TextField(blank=True, verbose_name='Naslovnica prvi del'),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='headline_second',
            field=models.TextField(blank=True, verbose_name='Naslovnica drugi del'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('donation_section', wagtail.core.blocks.StructBlock([('left_button_heading_part_one', wagtail.core.blocks.CharBlock(label='Levi gumb - Prvi del naslova', required=False)), ('left_button_heading_part_two', wagtail.core.blocks.CharBlock(label='Levi gumb - Drugi del naslova', required=False)), ('left_button_description', wagtail.core.blocks.CharBlock(label='Levi gumb - Podnaslov', required=False)), ('left_button_donation_page', wagtail.core.blocks.PageChooserBlock(label='Levi gumb - Povezava do strani')), ('right_button_heading_part_one', wagtail.core.blocks.CharBlock(label='Desni gumb - Prvi del naslova', required=False)), ('right_button_heading_part_two', wagtail.core.blocks.CharBlock(label='Desni gumb - Drugi del naslova', required=False)), ('right_button_description', wagtail.core.blocks.CharBlock(label='Desni gumb - Podnaslov', required=False)), ('right_button_donation_page', wagtail.core.blocks.PageChooserBlock(label='Desni gumb - Povezava do strani'))]))]),
        ),
    ]
