# Generated by Django 3.1.14 on 2022-01-24 21:21

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("home", "0041_auto_20220118_1149"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationembedpage",
            options={
                "verbose_name": "Donacijska stran z embedom",
                "verbose_name_plural": "Donacijske strani z embedom",
            },
        ),
        migrations.CreateModel(
            name="DonationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", wagtail.blocks.RichTextBlock())]
                    ),
                ),
                (
                    "left_box_heading_part_one",
                    models.TextField(
                        blank=True, verbose_name="Leva škatla - naslov prvi del"
                    ),
                ),
                (
                    "left_box_heading_part_two",
                    models.TextField(
                        blank=True, verbose_name="Leva škatla - naslov drugi del"
                    ),
                ),
                (
                    "left_box_description",
                    models.TextField(blank=True, verbose_name="Leva škatla - opis"),
                ),
                (
                    "left_box_button_text",
                    models.TextField(
                        blank=True, verbose_name="Leva škatla - gumb besedilo"
                    ),
                ),
                (
                    "right_box_heading_part_two",
                    models.TextField(
                        blank=True, verbose_name="Desna škatla - naslov drugi del"
                    ),
                ),
                (
                    "right_box_heading_part_one",
                    models.TextField(
                        blank=True, verbose_name="Desna škatla - naslov prvi del"
                    ),
                ),
                (
                    "right_box_description",
                    models.TextField(blank=True, verbose_name="Desna škatla - opis"),
                ),
                (
                    "right_box_button_text",
                    models.TextField(
                        blank=True, verbose_name="Desna škatla - gumb besedilo"
                    ),
                ),
                (
                    "left_box_button_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Leva škatla - gumb povezava",
                    ),
                ),
                (
                    "right_box_button_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Desna škatla - gumb povezava",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donacijska stran (z gumbi)",
                "verbose_name_plural": "Donacijske strani (z gumbi)",
            },
            bases=("wagtailcore.page",),
        ),
    ]
