# Generated by Django 3.1.14 on 2023-02-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_genericpage_headline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
    ]
