# Generated by Django 3.2 on 2024-08-06 09:48

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0046_auto_20240806_0935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", wagtail.blocks.RichTextBlock())], use_json_field=True
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="footer_links_left",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Če je prazno se uporabi naslov strani.",
                                        label="Ime",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(label="Stran"),
                                ),
                                (
                                    "has_border",
                                    wagtail.blocks.BooleanBlock(
                                        label="Gumb ima obrobo?", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                ("url", wagtail.blocks.URLBlock(label="Povezava")),
                                (
                                    "has_border",
                                    wagtail.blocks.BooleanBlock(
                                        label="Gumb ima obrobo?", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "email_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                (
                                    "email",
                                    wagtail.blocks.EmailBlock(label="Email povezava"),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
                verbose_name="Povezave v nogi na levi",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="footer_links_right",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Če je prazno se uporabi naslov strani.",
                                        label="Ime",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(label="Stran"),
                                ),
                                (
                                    "has_border",
                                    wagtail.blocks.BooleanBlock(
                                        label="Gumb ima obrobo?", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                ("url", wagtail.blocks.URLBlock(label="Povezava")),
                                (
                                    "has_border",
                                    wagtail.blocks.BooleanBlock(
                                        label="Gumb ima obrobo?", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "email_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                (
                                    "email",
                                    wagtail.blocks.EmailBlock(label="Email povezava"),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
                verbose_name="Povezave v nogi na desni",
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", wagtail.blocks.RichTextBlock())], use_json_field=True
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="navigation_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Če je prazno se uporabi naslov strani.",
                                        label="Ime",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(label="Stran"),
                                ),
                                (
                                    "has_border",
                                    wagtail.blocks.BooleanBlock(
                                        label="Gumb ima obrobo?", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                ("url", wagtail.blocks.URLBlock(label="Povezava")),
                                (
                                    "has_border",
                                    wagtail.blocks.BooleanBlock(
                                        label="Gumb ima obrobo?", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
                verbose_name="Povezave v glavi",
            ),
        ),
    ]
