# Generated by Django 3.1.14 on 2021-12-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Oznaka dosežka')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline_first', models.TextField(blank=True, verbose_name='Naslovnica prvi del')),
                ('headline_second', models.TextField(blank=True, verbose_name='Naslovnica drugi del')),
                ('headline_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Slika na naslovnici')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Naslov')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('link', models.URLField(verbose_name='Povezava do predloga zakona')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievements.achievementtag')),
            ],
        ),
    ]
