# Generated by Django 3.1.14 on 2021-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Povezava do predloga zakona'),
        ),
    ]
