# Generated by Django 3.1.14 on 2021-12-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_link_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementarchivepage',
            options={'verbose_name': 'Stran z dosežki', 'verbose_name_plural': 'Strani z dosežki'},
        ),
    ]
