# Generated by Django 3.1.14 on 2022-01-31 13:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_remove_achievement_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='link',
            field=wagtail.core.fields.StreamField([('page_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Če je prazno se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Stran')), ('has_border', wagtail.core.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Ime')), ('url', wagtail.core.blocks.URLBlock(label='Povezava')), ('has_border', wagtail.core.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('email_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Ime')), ('email', wagtail.core.blocks.EmailBlock(label='Email povezava'))]))], blank=True, null=True, verbose_name='Povezava'),
        ),
    ]
