# Generated by Django 3.1.14 on 2023-02-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_auto_20220720_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(verbose_name='Datum oz. končni datum, če gre za obdobje'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date2',
            field=models.DateField(blank=True, null=True, verbose_name='Začetni datum, če gre za obdobje (sicer naj ostane prazno)'),
        ),
    ]
