# Generated by Django 3.2 on 2024-08-06 09:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_auto_20230220_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='link',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Če je prazno se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Stran')), ('has_border', wagtail.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('external_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('url', wagtail.blocks.URLBlock(label='Povezava')), ('has_border', wagtail.blocks.BooleanBlock(label='Gumb ima obrobo?', required=False))])), ('email_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('email', wagtail.blocks.EmailBlock(label='Email povezava'))]))], blank=True, null=True, use_json_field=True, verbose_name='Povezava'),
        ),
    ]
