# Generated by Django 3.1.14 on 2024-01-24 12:05

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsarchivepage",
            name="projects",
            field=wagtail.fields.StreamField(
                [
                    (
                        "project",
                        wagtail.blocks.StructBlock(
                            [("project", wagtail.blocks.PageChooserBlock())]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
