# Generated by Django 3.1.14 on 2024-01-24 12:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsarchivepage',
            name='projects',
            field=wagtail.core.fields.StreamField([('project', wagtail.core.blocks.StructBlock([('project', wagtail.core.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
