# Generated by Django 3.1.4 on 2021-01-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novicapage',
            old_name='body',
            new_name='preview_text',
        ),
    ]
