# Generated by Django 3.1.4 on 2021-01-20 10:15

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novice", "0002_auto_20210120_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="novicapage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [
                                ("part_one", wagtail.blocks.CharBlock(required=False)),
                                ("part_two", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "intro_text",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                            ],
                            icon="title",
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                ],
                default="",
            ),
            preserve_default=False,
        ),
    ]
