# Generated by Django 3.1.4 on 2021-01-20 10:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novice', '0002_auto_20210120_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='novicapage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('part_one', wagtail.core.blocks.CharBlock(required=False)), ('part_two', wagtail.core.blocks.CharBlock(required=False)), ('intro_text', wagtail.core.blocks.RichTextBlock(required=False))], icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock())], default=''),
            preserve_default=False,
        ),
    ]
