# Generated by Django 3.1.14 on 2021-12-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("novice", "0005_auto_20211213_1320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novicaarchivepage",
            name="body",
        ),
        migrations.AddField(
            model_name="novicaarchivepage",
            name="headline_first",
            field=models.TextField(blank=True, verbose_name="Naslovnica prvi del"),
        ),
        migrations.AddField(
            model_name="novicaarchivepage",
            name="headline_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Slika na naslovnici",
            ),
        ),
        migrations.AddField(
            model_name="novicaarchivepage",
            name="headline_second",
            field=models.TextField(blank=True, verbose_name="Naslovnica drugi del"),
        ),
    ]
