# Generated by Django 3.1.14 on 2021-12-20 12:45

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novice", "0006_auto_20211220_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="novicapage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Opis"
            ),
        ),
        migrations.AlterField(
            model_name="novicapage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", wagtail.blocks.RichTextBlock())]
            ),
        ),
    ]
