# Generated by Django 3.1.14 on 2021-12-20 12:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novice', '0006_auto_20211220_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='novicapage',
            name='intro_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='novicapage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
