# Generated by Django 3.1.14 on 2021-12-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novice", "0008_novicapage_meta_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="novicaarchivepage",
            options={
                "verbose_name": "Seznam novic",
                "verbose_name_plural": "Seznami novic",
            },
        ),
        migrations.AlterModelOptions(
            name="novicapage",
            options={"verbose_name": "Novica", "verbose_name_plural": "Novice"},
        ),
    ]
