# Generated by Django 3.1.14 on 2021-12-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapublications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediapublicationspage',
            options={'verbose_name': 'Objave medijev', 'verbose_name_plural': 'Objave medijev'},
        ),
    ]
