# Generated by Django 3.1.14 on 2021-12-17 13:08

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_author_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="heading",
            field=models.TextField(blank=True, verbose_name="Naslov"),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Opis"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", wagtail.blocks.RichTextBlock())]
            ),
        ),
    ]
