# Generated by Django 3.1.14 on 2021-12-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211217_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='heading',
        ),
    ]
