# Generated by Django 3.1.14 on 2021-12-20 10:22

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_blogpage_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="related_blog_posts",
            field=wagtail.fields.StreamField(
                [
                    (
                        "blog_post",
                        wagtail.blocks.PageChooserBlock(
                            label="Povezava do blog zapisa"
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Povezani blog zapisi",
            ),
        ),
    ]
