# Generated by Django 3.1.14 on 2021-12-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('blog', '0007_blogpage_related_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='archive_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Povezava do seznama blog zapisov'),
        ),
    ]
