# Generated by Django 3.1.14 on 2021-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_archive_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='archive_page',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blogpost_archive_button',
            field=models.TextField(blank=True, verbose_name='Besedilo gumba za nazaj'),
        ),
    ]
