# Generated by Django 3.1.14 on 2021-12-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_auto_20211220_1650"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="blogpost_archive_button",
        ),
    ]
