# Generated by Django 3.1.14 on 2021-12-22 12:34

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("blog", "0010_remove_blogpage_blogpost_archive_button"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.author",
                verbose_name="Avtor",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", wagtail.blocks.RichTextBlock())], verbose_name="Besedilo"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(verbose_name="Datum"),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Opis pod naslovom"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="preview_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Slika",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="preview_text",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="Opis na seznamu"
            ),
        ),
    ]
