# Generated by Django 3.1.14 on 2021-12-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("blog", "0011_auto_20211222_1234"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG slika",
            ),
        ),
    ]
