# Generated by Django 3.1.14 on 2022-02-22 16:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220222_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='authors',
        ),
        migrations.CreateModel(
            name='BlogAuthorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.author')),
                ('blog', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author_relationship', to='blog.blogpage')),
            ],
        ),
    ]
